name: redux_persist_flutter
description: Redux Persist Flutter Integration with custom storage engines
version: 0.9.0
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: "flutter"
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  redux_persist: ^0.9.0

# Used for development
#dependency_overrides:
#  redux_persist:
#    path: ../redux_persist
